{
    "Service": "/EmployeeOffline/Services/abaprapsaml.service",
    "DefiningRequests": [{
        "Name": "Employee",
        "Query": "Employee"
    }],
    "_Type": "Action.Type.OfflineOData.Download",
    "ActionResult": {
        "_Name": "sync"
    },
    "OnFailure": "/EmployeeOffline/Actions/Service/SyncFailureMessage.action"
}