{
    "Service": "/EmployeeOffline/Services/abaprapsaml.service",
    "_Type": "Action.Type.OfflineOData.Upload",
    "ActionResult": {
        "_Name": "sync"
    },
    "OnSuccess": "/EmployeeOffline/Actions/Service/DownloadStartedMessage.action",
    "OnFailure": "/EmployeeOffline/Actions/Service/SyncFailureMessage.action"
}