{
    "Service": "/employeeinfo/Services/com_sunil_mdk_empinfo.service",
    "_Type": "Action.Type.ODataService.Initialize",
    "ShowActivityIndicator": true,
    "OnSuccess": "/employeeinfo/Actions/Service/InitializeOnlineSuccessMessage.action",
    "OnFailure": "/employeeinfo/Actions/Service/InitializeOnlineFailureMessage.action",
    "ActionResult": {
        "_Name": "init"
    }
}