{
    "Service": "/customerlist/Services/com_sunil_referenceapp.service",
    "_Type": "Action.Type.ODataService.Initialize",
    "ShowActivityIndicator": true,
    "OnSuccess": "/customerlist/Actions/Service/InitializeOnlineSuccessMessage.action",
    "OnFailure": "/customerlist/Actions/Service/InitializeOnlineFailureMessage.action",
    "ActionResult": {
        "_Name": "init"
    }
}