{
    "Service": "/overview/Services/es5.service",
    "_Type": "Action.Type.ODataService.Initialize",
    "ShowActivityIndicator": true,
    "OnSuccess": "/overview/Actions/Service/InitializeOnlineSuccessMessage.action",
    "OnFailure": "/overview/Actions/Service/InitializeOnlineFailureMessage.action",
    "ActionResult": {
        "_Name": "init"
    }
}